pipeline {
    agent any

    tools {
        maven 'M3'
    }

    options {
        skipStagesAfterUnstable()
        timestamps()
    }

    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                echo 'Deliver stage placeholder (Windows)'
                // Example:
                // bat 'copy target\\*.jar C:\\deployments\\'
            }
        }
    }
}
